version: 2.1

jobs:
  build:
    docker:
      - image: ghcr.io/cirruslabs/flutter:beta
    environment:
      ANDROID_HOME: /opt/android-sdk
    steps:
      - checkout

      - run:
          name: Install Android Build Tools
          command: sdkmanager "build-tools;34.0.0" "ndk;26.3.11579264"

      - run:
          name: Flutter Doctor
          command: flutter doctor

      - run:
          name: Flutter Get
          command: flutter pub get

      - run:
          name: Analyze
          command: flutter analyze
          
      - run:
          name: Run Tests
          command: flutter test

      - run:
          name: Build APK
          command: flutter build apk --debug

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
