version: 2.1

jobs:
  build:
    docker:
      - image: cirrusci/flutter:stable  # Imagem Docker com Flutter instalado
    steps:
      - checkout
      
      - run:
          name: Flutter Doctor
          command: flutter doctor

      - run:
          name: Analyze
          command: flutter analyze

      - run:
          name: Run Tests
          command: flutter test

      - run:
          name: Build APK
          command: flutter build apk --debug

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
