version: 2.1

jobs:
  build:
    docker:
      - image: ghcr.io/cirruslabs/flutter:beta
    resource_class: medium  # ou medium+ se possível
    steps:
      - checkout

      - run:
          name: Flutter Version
          command: flutter --version

      - run:
          name: Flutter Doctor
          command: flutter doctor

      - run:
          name: Get Dependencies
          command: flutter pub get

      - run:
          name: Analyze
          command: flutter analyze

      - run:
          name: Run Tests
          command: flutter test

      - run:
          name: Build APK (No Daemon)
          command: flutter build apk --debug --no-daemon

workflows:
  version: 2
  build_and_test:
    jobs:
      - build